
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://uaptkggmrsxoqayjjnlz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcHRrZ2dtcnN4b3FheWpqbmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODc1MTgsImV4cCI6MjA2NTQ2MzUxOH0.SLWMEMq8Y4Yzncv7nccQUy1ufMbk5Gd7H7eSjHl-w_0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
